let a = 55;
let b = 5;
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(a / b);
console.log(a % b);
c=5;
c++;
console.log('c is 5 after incerement : '+c);
c--;
console.log('c is 6 after decrement : '+c);
console.log(a != b);
console.log(a == b);
console.log('a' === a);
console.log('a' + 'b');
c=5;
console.log(c+=5);
console.log(c-=5);
console.log(c*=5);
console.log(c/=5);
console.log(6>5);
console.log(6<5);
console.log(6>=6);
console.log(6<=5);